blog/urls.py
from django.urls import path, include
from . import views
app_name  = 'blog'
urlpatterns = [
     #blogs and etc
    path('', views.AllBlogs, name='AllBlogs'),

    #blogs in detail
    path('<str:slug>', views.detail, name='detail'),


]

sid/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.views.static import serve


admin.site.site_header = "Sid's Blogs"
admin.site.site_title = "Sid's Admin Panel"
admin.site.index_title = "Welcome to Sid's Admin Panel"

urlpatterns = [
    # admin panel
    path('AdminPanel/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('api/',include('sid.apiUrls')),
    # contact page
    path('contact', views.contact, name='contact'),

    path('aboutme', views.aboutme, name='aboutme'),


    # comment and reply on blog
    path('postComment', views.postComment, name='postComment'),

    # search in blogs
    path('search', views.search, name='search'),

    # user login , singup , logout
    path('singup', views.handleSingup, name='singup'),
    path('checkForUserName', views.checkForUserName, name='checkForUserName'),
    path('checkForUserMail', views.checkForUserMail, name='checkForUserMail'),
    # login
    path('login', views.handleLogin, name='handleLogin'),
    path('logout', views.handelLogout, name="handleLogout"),
    path('logout', views.handelLogout, name="handleLogout"),
    path('reset_password', auth_views.PasswordResetView.as_view(
        template_name='Extra/Reset_Email_card.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(
        template_name='Extra/Reset_Email_Sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='Extra/Reset_password_form.html'), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='Extra/Reset_password_done.html'), name='password_reset_complete'),


    # privacy_policy
    path('Privacy_Policy', views.Privacy_Policy, name='Privacy_Policy'),


    # email updates newsletter
    path('newsletter', views.newsletter, name='newsletter'),

    # home page
    path('home', views.home, name='home'),
    path('', views.home, name='home'),
    path('subscription', views.subscription, name='subscription'),




    re_path(r'^DataBase/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),

    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),



   

]

handler404 = 'sid.views.error_404_view'

blog/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User

from autoslug import AutoSlugField
from django.core.validators import FileExtensionValidator

# Create your models here.


class webData(models.Model):
    site_name = models.CharField(max_length=50)
    About_me = models.TextField()
    mine_name = models.CharField(max_length=50)
    HomePage_qoute = models.TextField()
    email = models.EmailField(max_length=254)
    # slide_img = models.ManyToManyField(sliderImages)
    my_image = models.ImageField(upload_to='Images/WebData')

    slider1 = models.ImageField(upload_to='Images/WebData', null=True)
    Socail = models.URLField(max_length=200, null=True)

    def __str__(self):
        return self.mine_name

# many to many fieleds
class tag(models.Model):
    created_on = models.DateField(auto_now=True, editable=False)
    tag = models.CharField(max_length=50)

    def __str__(self):
        return self.tag

TYPE_CHOICES = (
    ('tool','TOOL'),
    ('framework', 'FRAMEWORK'),
    ('library','LIBRARY'),
    ('language ','LANGUAGE'),
)
class ProjectTools(models.Model):
    created_on = models.DateField(auto_now=True, editable=False)
    toolName = models.CharField(max_length=50)
    logo = models.FileField(upload_to="Images/Tools", validators=[FileExtensionValidator(['svg'])])
    publish = models.BooleanField(default=True)
    type = models.CharField(max_length=20, choices=TYPE_CHOICES, default='tool')
    def __str__(self):
        return self.toolName
    

class Blog(models.Model):
    image = models.ImageField(upload_to='Images/BlogImages', null=True)
    title = models.CharField(max_length=150)
    slug = AutoSlugField(populate_from='title')
    summary = models.TextField(max_length=250, null=True)
    publish_date = models.DateTimeField(auto_created=True, auto_now_add=True)
    body = models.TextField()
    tags = models.ManyToManyField(tag)
    author = models.ForeignKey(User,on_delete=models.PROTECT,default=5)
    views = models.IntegerField(default=0)
    publish = models.BooleanField(default=True)

    def __str__(self):
        return self.title+' | ' + self.author.first_name


class BlogComment(models.Model):
    sno = models.AutoField(primary_key=True)
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Blog, on_delete=models.CASCADE)
    # parent = models.ForeignKey('self', on_delete=models.CASCADE , null=True , default='none')
    timeStamp = models.DateTimeField(default=now)
    parent = models.ForeignKey("self", null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment[0:15] + '...' + " by " + self.user.username + ' on  blog(title)-' + self.post.title


class Subscribers(models.Model):
    email = models.EmailField(null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class MailMessage(models.Model):
    title = models.CharField(max_length=100, null=True)
    message = models.TextField(null=True)

    def __str__(self):
        return self.title


class ContactMe(models.Model):
    Full_Name = models.CharField(max_length=25, null=False)
    Email_Id = models.EmailField(null=False)
    Message_To_Me = models.TextField(null=False)
    Contacted_On = models.DateTimeField(default=now)

    def __str__(self):
        return self.Full_Name + "|" + str(self.Contacted_On)


class Projects(models.Model):
    name = models.CharField(max_length=50)
    summary = models.TextField()
    projectType = models.CharField(max_length=50)
    skills = models.CharField(max_length=50)
    doneOn = models.CharField(max_length=50)
    Thumbnail = models.ImageField(upload_to='Images/Projects/Thumbnail')
    link = models.URLField(max_length=200)
    tools = models.ManyToManyField(ProjectTools)
    def __str__(self):
        return self.name

templates/all blogs.html
{% extends 'base_layout.html' %}
{%load static%}
{% block content %}
<div class="container my-3">
    <h3 class="py-3">All Blog Posts <i class="bi bi-folder2-open"></i></h3>
    <div class="row d-flex align-items-stretch" id="Blogs">
        {%include 'card2.html'%}
    </div>

</div>

{%endblock%}
{% block scripts %}
<!-- <script src={% static 'js/AllBlogs.js' %}></script> -->
<script>
    document.getElementById('loadMoreBtn').onsubmit = () => {
        document.getElementById('loadMoreBtn_Span').innerHTML = `
<div class="row w-100 my-3 mx-auto">
    <div class="spinner-border text-user-primary-100" role="status">
  <span class="sr-only">Loading...</span>
</div>
</div>`;
    }
</script>
{% endblock scripts %}

templates/card.html
<div class="col-lg-4 col-sm-4 col-12  py-3 d-flex">
    <div class="card">
        <img src="{{post.image.url}}" class="card-img-top" alt="{{post.title}}" style="height:35vh;">
        <div class="card-body pb-4 d-flex flex-column">
            <div class="my-auto ">
                <p class="card-title text-capitalize font-weight-bold h5">{{post.title}}</p>
                <div class="my-1">

                    <small class='font-weight-light bi bi-calendar-event'> {{post.publish_date|date:'d M Y'}}</small>
                    <small class="bi bi-eye-fill float-right " style="opacity: 0.9; cursor: default;"
                        title='{{post.views}} views' data-toggle="tooltip" data-placement="top">&nbsp;{{post.views}}
                    </small>
                </div>
            </div>
            <div class=" my-auto">
                <whr></whr>
            </div>
            <div class="my-auto">
                <span>

                    <p class="card-text ">
                        {{post.summary|truncatewords:30|striptags}}</p>
                    <br>
                    <small class="pt-3 mb-4 ">
                        <span class="tags mt-0 mb-2 d-flex  flex-wrap  justify-content-start h6">
                            {%for tag in post.tags.all%}
                            <a href="{%url 'search'%}?query={{tag}}"
                                class="badge badge-Theme-Primary bi bi-tag-fill w-auto my-1 mr-2 text-capitalize">
                                {{tag}}</a>
                            {%endfor%}
                        </span>

                        <br>
                    </small>
                </span>
                <!-- Link -->

                <a href="{% url 'blog:detail' slug=post.slug %}" class="button-arrow float-right ">
                    Read more
                </a>
            </div>
        </div>
    </div>
</div>

templates/card2.html
{% for post in posts%}
<div class="col-lg-6 col-sm-6 col-12 my-lg-3 my-sm-3 my-2 d-flex">
    <div class="card-deck">
        <div class="card">
            <img class="card-img-top" src={{post.image.url}} alt={{post.title|safe}} style="max-height: 250px;">
            <div class="card-body">
                <p class="card-title h5">{{post.title|safe}}</p>
                <whr></whr>
                <p class="card-text"></i>{{post.summary|truncatewords:45|striptags}}</p>

            </div>
            <div class="card-body pb-2">
                <span class="tags my-2 d-flex  flex-wrap  justify-content-start ">
                    {%for tag in post.tags.all%}
                    <a href="{%url 'search'%}?query={{tag}}"
                        class="badge badge-Theme-Primary bi bi-tag-fill w-auto my-1 mr-2 text-capitalize"> {{tag}}</a>
                    {%endfor%}
                </span>
                <span class="my-auto d-flex justify-content-between pt-2">
                    <span class="bi bi-eye-fill  my-auto" style="font-size: medium;opacity: 0.9; cursor: default;"
                        title='{{post.views}} views' data-toggle="tooltip"
                        data-placement="bottom">&nbsp;{{post.views}}</span>
                    <!-- Link -->
                    <a href="{% url 'blog:detail' slug=post.slug %}" class="button-arrow">
                        Read more
                    </a>
                </span>
            </div>
            <div class="card-footer d-flex justify-content-between">
                <small class="text-user">Last updated {{post.publish_date|date:'d M Y'}}</small>
                <small class="text-user text-capitalize"><i class="bi bi-person-fill "></i> Author -
                    {{post.author.first_name}}</small>
            </div>
        </div>
    </div>
</div>
{%endfor%}
{%if posts.has_next%}
<span id="loadMoreBtn_Span">
    <div class="row w-100 my-3 mx-auto">
        <button class=" btn btn-user-primary w-auto mx-auto htmx-request" id="loadMoreBtn"
            hx-get="?page={{ posts.next_page_number }}" hx-target="#loadMoreBtn_Span" hx-trigger="click "
            hx-swap="outerHTML" hx-indicator=".progress">Load More
        </button>
    </div>
</span>
{%else%}
<div class="row w-100 my-3 mx-auto">
    <div class="alert alert-primary text-center mx-auto" role="alert" id="noMoreAlert">
        All Done ✔. No More Blogs To Load!
    </div>
</div>
{%endif%}

templates/detail.html
{% extends 'base_layout.html' %}
{% load extras_filter %}
{% block content %}
{% load static %}
{% block index %}
<title>{{data.site_name}} | {{blog.title}} </title>
{% endblock index %}
{%block csslinks%}
<link rel="stylesheet" href={% static 'css/detailStyle.css' %}>
<style>

</style>
{%endblock csslinks%}
<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center text-capitalize" id="blog-title">{{blog.title}}</h2>
            <h6 class="float-left"><i class="bi bi-clock-history"></i> {{blog.publish_date|date:'d M,Y'}}</h6>
            <span class="text-capitalize float-right"><i class="bi bi-person-fill"></i>author - {{blog.author.first_name}}</span>
            <span class="float-right" style="font-size: medium;cursor: default;" title='{{post.views}} views'><i
                    class="bi bi-eye-fill"></i> {{blog.views}}&nbsp;|&nbsp;</span>

        </div>

    </div>
    <div class="row ">
        <div class="col-12 w-100 my-3">
            <div class="blog-image d-flex">
                <img src={{blog.image.url}} alt="" class="img-fluid mx-auto  my-3 ">
            </div>
            <div class="" id="body_content">
                {{blog.body|safe}}
            </div>
        </div>
        <br>
        <div class="col-12">
            {%for tag in blog.tags.all%}
            <a href="{%url 'search'%}?query={{tag}}" class="badge badge-Theme-Primary bi bi-tag-fill w-auto my-1 mr-2">
                {{tag}}</a>
            {%endfor%}
        </div>
    </div>
    <hr>
</div>

<div class="container mt-5">
    <p class="h6 ">
        Suggested Blogs -
    </p>
</div>

<div class="container mb-5 overflow-auto">

    <div class="row d-flex flex-nowrap flex-row" id="moreBlogs">
        {%for blog in moreBlogs %}
        <div class="col-lg-4 col-5 col-sm-5 my-3">

            <a href="{% url 'blog:detail' slug=blog.slug %}" class="position-relative">
                <img src="{{blog.image.url}}" class="img-bordered img-fluid img-thumbnail w-100 h-100"
                    alt="{{blog.title}}" title="{{blog.title}}" data-toggle="tooltip" data-placement="auto">
            </a>
        </div>
        {%endfor%}
    </div>
</div>
<!-- commnets -->
<div class="container py-2  mt-3" id="commentes">
    <span class="h5 ">Comments <i class="bi bi-chat-dots"></i> ({{comments.count}}) </span>
    <span class="text-center float-end font-weight-normal  text-capitalize ">comment and share if you found this
        article to be helpful!
    </span>
    <div class="row w-100 my-3 py-3 border-top border-bottom mx-0 py-0 ">
        <!-- if else for comment box -->
        {% if request.user.is_authenticated %}
        <div class="col-lg-2 col-sm-2 col-3 my-auto mx-auto text-center">
            <i class="bi bi-pencil-square" style="font-size: 4vh;"></i>
            <br>
            <small>write your comment</small>
        </div>

        <div class="col-lg-10 col-sm-10 col-9 mx-auto text-capitalize">

            <form hx-post="{%url 'postComment'%}" hx-trigger="submit " hx-target="#comment_container" hx-swap="innerHTML" hx-indicator=".progress">
                {% csrf_token %}
                <div class="form-floating">
                    <textarea class="form-control" placeholder="Leave a comment here" name="Postcomment" id="commandBox"
                        style="height: 100px" required></textarea>
                    <label for="commandBox">Comments</label>
                </div>
                <input type="hidden" name="PostSno" value="{{blog.id}}">
                <input type="hidden" name="PostSlug" value="{{blog.slug}}">
                <input type="hidden" name="parentSno" value="{{comment.sno}}">
                <button type="submit" class=" btn btn-user-primary my-2">Post Comment</button>
            </form>

        </div>
        <!-- login if not to comment -->
        {% else %}
        <div class="col-lg-2 col-sm-2 col-3 my-auto mx-auto text-center">
            <i class="bi bi-person-x-fill" style="font-size: 6vh;"></i>
            <br>
            Login Required
            <br>
        </div>
        <div class="col-lg-10 col-sm-10 col-9 mx-auto text-capitalize text-center text-lg-left text-sm-left "
            style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">
            <h4 class="text-center" style="font-size: 300;">In Order to write your comment you need to login first.
            </h4>
            <div class="login singup d-flex justify-content-center">
                <div class="userlogo  my-auto nav-item mx-1">
                    <a href="{%url 'handleLogin'%}" target="_blank"><button
                            class="btn btn-user-primary nav-link px-3 mx-0" type="submit"> Login <i
                                class="bi bi-box-arrow-in-right"></i></button></a>
                </div>
                <div class="userlogo  my-auto nav-item mx-1">
                    <a href="{%url 'singup'%}" target="_blank"><button class="btn btn-user-primary nav-link px-3 mx-0"
                            type="submit"> Singup <i class="bi bi-person-plus-fill"></i></button></a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>


    </div>
<div class="container-lg  container-fluid " id="comment_container">
    <!-- comments made before -->
    {%include 'blog/comment.html'%}
</div>

{% endblock %}
{% block scripts %}
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script src="{%static 'js/commentHandel.js'%}"></script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-61a286a175bf78d5"></script>
{% endblock scripts %}

templates/home.html
{% extends 'base_layout.html' %}
{% load static %}
{%block csslinks%}
<link rel="stylesheet" href={% static 'css/style.css' %}>
<link rel="stylesheet" href={% static 'css/typed.css' %}>

{%endblock csslinks%}
{% block content %}

<div class="section1 ">
    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="container-fluid my-auto" id="carousel-continer"
            style="background-image:linear-gradient(to bottom, rgba(5, 26, 56, 0.75),
        rgb(12, 37, 62,0.75), rgb(24, 48, 68,0.75), rgb(39, 60, 73,0.75), rgb(55, 71, 79,0.75)),url('{{data.slider1.url}}');min-height: 100vh;">
            <div class="row">
                <div class="col-12 mt-lg-5 text-center">
                    <h1 class="text-capitalize py-lg-2 py-sm-2 py-2 mt-5">hello {% if user.is_authenticated %}
                        <span class="font-weight-bold"><b style="color:whitesmoke;">{{user.first_name}}</b>,
                        </span>
                        {% else %}
                        there,
                        {% endif %}<br>welcome to {{data.site_name}}.
                    </h1>
                    <h4>My self <span><a href="{{data.Socail}}" target="_blank"
                                rel="noopener noreferrer" class="link">{{data.mine_name}}</a>.</span></h4>
                    <p id="typedTextP" class="mt-2">I Am <span class="typed-text"></span><span
                            class="cursor">&nbsp;</span></p>
                    <br>
                    <h5 class="text-white mx-auto my-lg-5 font-weight-lighter slider-quote" id="quote"><i
                            class="fa fa-quote-left text-light"></i>{{data.HomePage_qoute}} <i
                            class="fa fa-quote-right text-light"></i></h5>

                </div>
            </div>
        </div>

    </div>
</div>
<div class="section2">
    <div class="container-fluid my-5">
        <div class="row ">
            <div class="col-lg-8 col-sm-8 col-12 order-lg-1 order-sm-1  py-2 order-3 ">

                <div class="card py-5 text-center">
                    <p class="card-header-tabs  text-capitalize mx-auto h3">What is {{data.site_name}}.</p>
                    <div class="card-body pb-0">
                        <p class="card-title px-lg-5 pb-2">I created {{data.site_name}} to share my experiences about
                            web
                            development, computer science, mathematics, and life. As well as sports, food, nature, and
                            tech, I am passionate about writing about these topics as well. </p>
                        <a href="{%url 'blog:AllBlogs'%}" class="button-primary   text-capitalize">Browse all posts</a>

                    </div>
                </div>
                <div class="card py-5 mt-3 text-center order-2">
                    <h2 class="card-header-tabs font-weight-bolder text-capitalize mx-auto"></h2>
                    <div class="card-body">
                        <p class="card-title pb-2">
                            Please feel free to check out my <a href="https://www.instagram.com/sudarshan_kakde_/"
                                class="link" target="_blank" rel="noopener noreferrer">Instagram account </a> or connect
                            with me on <a href="https://linkedin.com/in/sudarshan-kakde-510b15194" target="_blank"
                                rel="noopener noreferrer" class="link">LinkedIn.</a> <br>
                            It's always exciting to work with like-minded people,<br>
                            let's discuss over <a href="https://www.buymeacoffee.com/sudarshankakde" target="_blank"
                                rel="noopener noreferrer" class="link">Coffee </a>.

                        </p>
                        <a href="https://github.com/sudarshankakde" target="_blank" rel="noopener noreferrer"
                            class=" p-2  mt-2 mb-0  text-capitalize icon-link">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                                stroke-linejoin="round" class="feather feather-github">
                                <path
                                    d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22">
                                </path>
                            </svg></a>
                        <a href="mailto:sudarshankakde1111@gmail.com" target="_blank" rel="noopener noreferrer"
                            class=" p-2  mt-2 mb-0  text-capitalize icon-link">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                                stroke-linejoin="round" class="feather feather-mail">
                                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z">
                                </path>
                                <polyline points="22,6 12,13 2,6"></polyline>
                            </svg></a>
                        <a href="https://instagram.com/sudarshan_kakde_" target="_blank" rel="noopener noreferrer"
                            class="p-2  mt-2 mb-0  text-capitalize icon-link">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                                stroke-linejoin="round" class="feather feather-instagram">
                                <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                                <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                                <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
                            </svg>
                        </a>
                        <a href="{{data.Socail}}" target="_blank" rel="noopener noreferrer"
                            class="p-2  mt-2 mb-0  text-capitalize icon-link">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                                stroke-linejoin="round" class="feather feather-link">
                                <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path>
                                <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path>
                            </svg>
                        </a>

                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-4 col-12 text-center  order-lg-2 order-sm-2 py-2 order-1">
                <div class="aboutme ">
                    <h5>ABOUT ME</h5>
                </div>
                <div class="card mx-auto my-3 py-3" style="width: 100%;">
                    <img src={{data.my_image.url}} class="card-img-top mx-auto my-auto w-75 shadow " alt="{{data.mine_name}}">
                    <div class="card-body">
                        <div class="card-title">
                            <h4>{{data.mine_name}}</h4>
                        </div>
                        <hr>
                        <p class="card-text">
                            <i class="fa fa-quote-left" aria-hidden="true"></i>
                            {{data.About_me|safe}} <i class="fa fa-quote-right" aria-hidden="true"></i>
                        </p>
                        <a href="{%url 'aboutme'%}" class="button-primary px-2">
                            More About Me
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section3">
    <h2 class="mx-3" id="latestpost"><i class="fa fa-clock"></i> Latest Posts.</h2>
    <div class="container-fluid mb-5">
        <div class="row d-flex align-items-stretch mx-auto">
            {%for post in posts.all%}
            {% include "card.html" %}
            {%endfor%}
        </div>
    </div>
    <!-- popular posts -->
    <h2 class="mx-3 text-capitalize" id="latestpost"><i class="fa fa-fire " style="color: #e25822;"></i> popular Posts.
    </h2>
</div>
<div class="container-fluid">
    <div class="row  d-flex align-items-stretch mx-auto">
        {%for post in PopularPosts.all%}
        {% include "card.html" %}

        {%endfor%}
    </div>
</div>

<div class="container mx-auto card mt-4" id="Subscribe" data-aos="flip-right">
    <div class="row ">
        <div class="col-11 mx-auto w-100 text-center p-lg-5 p-sm-5 py-5 ">
            <h3>Subscribe to my newsletter! </h3>
            <h6 class="mb-4">So that you never miss any update <i class="bi bi-envelope"></i></h6>

            <form hx-post="/subscription" hx-trigger="submit" hx-target="#parent-div" hx-swap="innerHTML" hx-indicator=".progress"
                id="subscriptionForm">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="email" class="form-control" placeholder="Your Email" aria-label="Your Email"
                        aria-describedby="basic-addon2" name="SubscriptionEmail" required>
                    <div class="input-group-append">
                        <button class="btn  btn-user-primary" type="submit">Subscribe <i
                                class="bi bi-bell-fill"></i></button>
                    </div>
                </div>
                <div id="parent-div" class="text-white-50"></div>
            </form>
        </div>
    </div>
</div>
<script>
    document.getElementById('subscriptionForm').onsubmit = () => {
        document.getElementById('parent-div').innerHTML = `<div class="spinner-border text-user-primary-100" role="status">
  <span class="sr-only">Loading...</span>
</div>`;
    }
</script>
{% endblock content %}
{% block scripts %}


{% endblock scripts %}

templates/newsletter.html
{% extends 'base_layout.html' %}
{% block index %}
<title>{{data.site_name}} Newsletter</title>
{% endblock index %}
{% block content %}
{% load static %}

<div class="container my-5" style="">
    <div class="row">
        <div class="col-12">
            {% if user.is_superuser %}
            <div class="newsletter">
                <form action="/newsletter" method="post">
                    {% csrf_token %}
                    <div class="">
                        <h5>title</h5>
                        <input class="form-control" type="text" name="title" id="title">
                        <h5>message</h5>
                        <textarea class="form-control" name="message" id="id_body" cols="30" rows="10"></textarea>
                        <br>
                    </div>
                    <button type="submit" class="btn btn-user-primary">send newsletter</button>
                </form>
            </div>
            {%else%}
            <div class="container" id="Subscribe">
                <div class="row">
                    <div class="col-12 mx-auto w-100 text-center p-lg-5 p-sm-5 py-5 card">
                        <h3>Subscribe to my newsletter !</h3>
                        <h6>So that you never miss any update.</h6>
                        <form action="/home#Subscribe" method="post">
                            {% csrf_token %}
                            <div class="input-group my-3">
                                <input type="email" class="form-control " placeholder="Your Email"
                                    aria-label="Your Email" aria-describedby="basic-addon2" name="SubscriptionEmail">
                                <div class="input-group-append">
                                    <button class="btn  btn-user-primary" type="submit">Subscribe <i
                                            class="bi bi-bell"></i></button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            {%endif%}
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-12 text-center mt-5 card p-4 ">
            <h3 class="">Why to Subscribe Newsletter ?</h3>
            <b>Subscribing to newsletters will ensure you never miss any interesting posts on blogs. By subscribing to
                our newsletter, you are ahead of the game.
            </b>
        </div>
    </div>
</div>

{%endblock%}

{% block scripts %}
<!-- <script src={% static 'js/tinyInject.js' %}></script> -->
{% endblock scripts %}